# ============================================================
# Liver healthy-tissue recurrence analysis - miRNA
#
# Author: MAM
# Date: April 2026
#
# Description:
# This script reproduces the healthy tissue–based recurrence analyses
# for miRNA data, using the same preprocessing and modelling logic as
# the submission-ready tumour miRNA and healthy mRNA scripts.
#
# Input:
# - data/merge_mirna.csv
# - data/mRNA_miRNA_patient_sample_info.csv
# - results/healthy_program_scores_mRNA.csv   (generated by healthy mRNA script)
#
# Output:
# - Figures (PDF) in results/figures/
# - Processed objects (.rds) in results/objects/
# - Summary tables (.csv) in results/
#
# Notes:
# - One predefined outlier sample (X46_B040_80_Normal) is excluded.
# - TCGA miRNA sample IDs are kept as-is.
# - Non-TCGA metadata sample IDs are converted from dot-separated to
#   underscore-separated format to match the miRNA expression matrix.
# ============================================================

# ============================================================
# 0. Setup
# ============================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(mixOmics)
  library(randomForest)
  library(pROC)
  library(scales)
  library(grid)
  library(dplyr)
  library(tidyr)
  library(ggpubr)
  library(rstatix)
})

set.seed(999)

# Project directories
input_dir   <- "data"
output_dir  <- "results"
figure_dir  <- file.path(output_dir, "figures")
object_dir  <- file.path(output_dir, "objects")

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(figure_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(object_dir, showWarnings = FALSE, recursive = TRUE)

# Input files
expression_file <- file.path(input_dir, "merge_mirna.csv")
metadata_file   <- file.path(input_dir, "mRNA_miRNA_patient_sample_info.csv")
program_file    <- file.path(output_dir, "healthy_program_scores_mRNA.csv")

# Predefined QC exclusion
bad_sample <- "X46_B040_80_Normal"

# ============================================================
# 1. Load and preprocess data
# ============================================================

message("Loading miRNA matrix and metadata...")

# Keep default column-name conversion for miRNA expression data,
# as in the tumour miRNA script
expr_raw <- read.csv(expression_file, stringsAsFactors = FALSE)

# Keep metadata names unchanged
metadata <- read.csv(metadata_file, stringsAsFactors = FALSE, check.names = FALSE)

# Remove miRNAs with missing/empty identifiers
expr_clean <- expr_raw[!(is.na(expr_raw[[1]]) | expr_raw[[1]] == ""), ]

# Remove miRNAs with zero expression across all samples
expr_clean <- expr_clean[rowSums(expr_clean[, -1] != 0) > 0, ]

# Extract sample IDs from expression matrix
sample_ids <- colnames(expr_clean)[-1]
sample_ids_clean <- trimws(sample_ids)

# Use the same metadata ID logic as in the submission-ready miRNA script
metadata_ids_clean <- trimws(as.character(metadata[[1]]))
metadata_ids_match <- ifelse(
  grepl("^TCGA", metadata_ids_clean),
  metadata_ids_clean,
  gsub("\\.", "_", metadata_ids_clean)
)

sample_ids_match <- sample_ids_clean

# Build lookup tables
recurrence_lookup <- setNames(metadata$Recidiv, metadata_ids_match)
tissue_lookup     <- setNames(metadata$Tumour, metadata_ids_match)

# Match sample-level labels to the expression matrix
recurrence_labels <- sapply(sample_ids_match, function(id) {
  value <- recurrence_lookup[id]
  if (is.na(value)) return(NA_character_)
  if (value == 1) return("Recidivism")
  if (value == 0) return("Remission")
  return(NA_character_)
})

tissue_labels <- sapply(sample_ids_match, function(id) {
  value <- tissue_lookup[id]
  if (is.na(value)) return(NA_character_)
  if (value == 1) return("Tumour")
  if (value == 0) return("Healthy")
  return(NA_character_)
})

message("Number of expression samples: ", length(sample_ids_clean))
message("Matched recurrence labels: ", sum(!is.na(recurrence_labels)))
message("Matched tissue labels: ", sum(!is.na(tissue_labels)))

# Build samples x miRNAs numeric matrix
expr_matrix <- apply(expr_clean[, -1], 2, as.numeric)
expr_matrix <- t(expr_matrix)
rownames(expr_matrix) <- sample_ids_clean
colnames(expr_matrix) <- make.unique(expr_clean[[1]])

# Remove samples with missing labels
valid_samples <- !is.na(recurrence_labels) & !is.na(tissue_labels)

if (sum(valid_samples) == 0) {
  stop("No samples remained after matching miRNA data to metadata. Check sample ID formatting and metadata sample ID column.")
}

expr_matrix <- expr_matrix[valid_samples, , drop = FALSE]
recurrence_labels <- factor(recurrence_labels[valid_samples], levels = c("Remission", "Recidivism"))
tissue_labels     <- factor(tissue_labels[valid_samples], levels = c("Healthy", "Tumour"))

# Remove zero-variance miRNAs across retained samples
expr_matrix <- expr_matrix[, apply(expr_matrix, 2, function(x) sd(x, na.rm = TRUE) > 0), drop = FALSE]

# Log-transform expression values
mode(expr_matrix) <- "numeric"
log_expr_matrix <- log2(expr_matrix + 1)

# Assign names to label vectors
names(recurrence_labels) <- rownames(log_expr_matrix)
names(tissue_labels)     <- rownames(log_expr_matrix)

# Remove predefined outlier sample
if (!is.na(bad_sample) && bad_sample %in% rownames(log_expr_matrix)) {
  log_expr_matrix <- log_expr_matrix[rownames(log_expr_matrix) != bad_sample, , drop = FALSE]
  recurrence_labels <- recurrence_labels[names(recurrence_labels) != bad_sample]
  tissue_labels     <- tissue_labels[names(tissue_labels) != bad_sample]
}

# Rebuild source labels from sample names
source_labels <- factor(
  ifelse(grepl("^TCGA", rownames(log_expr_matrix)), "TCGA", "KI"),
  levels = c("KI", "TCGA")
)
names(source_labels) <- rownames(log_expr_matrix)

# Restrict healthy-only dataset
healthy_samples <- names(tissue_labels)[tissue_labels == "Healthy"]
expr_healthy    <- log_expr_matrix[healthy_samples, , drop = FALSE]
labels_healthy  <- recurrence_labels[healthy_samples]

# Save processed objects
saveRDS(log_expr_matrix, file.path(object_dir, "healthy_mirna_log_expr_matrix.rds"))
saveRDS(recurrence_labels, file.path(object_dir, "healthy_mirna_recurrence_labels.rds"))
saveRDS(tissue_labels, file.path(object_dir, "healthy_mirna_tissue_labels.rds"))
saveRDS(source_labels, file.path(object_dir, "healthy_mirna_source_labels.rds"))
saveRDS(expr_healthy, file.path(object_dir, "healthy_mirna_expr_healthy.rds"))
saveRDS(labels_healthy, file.path(object_dir, "healthy_mirna_labels_healthy.rds"))

# ============================================================
# 1B. Cohort summary table
# ============================================================

sample_summary <- data.frame(
  SampleID = rownames(log_expr_matrix),
  Cohort = ifelse(grepl("^TCGA", rownames(log_expr_matrix)), "TCGA", "KI"),
  Tissue = tissue_labels,
  Outcome = recurrence_labels,
  stringsAsFactors = FALSE
)

write.csv(sample_summary, file.path(output_dir, "healthy_mirna_sample_summary.csv"), row.names = FALSE)

sample_counts <- sample_summary %>%
  count(Cohort, Tissue, Outcome)
write.csv(sample_counts, file.path(output_dir, "healthy_mirna_sample_counts.csv"), row.names = FALSE)

# ============================================================
# 2. Utility functions
# ============================================================

plot_plsda_scores <- function(plsda_fit, y, title_text) {
  scores_df <- data.frame(
    Comp1 = plsda_fit$variates$X[, 1],
    Comp2 = plsda_fit$variates$X[, 2],
    Outcome = factor(y, levels = c("Remission", "Recidivism"))
  )
  
  ggplot(scores_df, aes(x = Comp1, y = Comp2, fill = Outcome)) +
    geom_point(shape = 21, size = 3, color = "black", stroke = 0.6) +
    scale_fill_manual(values = c("Remission" = "#377EB8", "Recidivism" = "#E41A1C")) +
    theme_minimal(base_size = 14) +
    labs(
      title = title_text,
      x = "PLS-DA Component 1",
      y = "PLS-DA Component 2"
    ) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black"),
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.title = element_blank()
    )
}

plot_roc_curve <- function(roc_obj, auc_val, ci_vals = NULL, title_text, color_value) {
  if (!is.null(ci_vals)) {
    label_text <- sprintf(
      "AUC = %.3f\n95%% CI: %.3f-%.3f",
      auc_val,
      ci_vals[1],
      ci_vals[3]
    )
  } else {
    label_text <- sprintf("AUC = %.3f", auc_val)
  }
  
  ggroc(roc_obj, legacy.axes = TRUE, color = color_value, linewidth = 1.2) +
    coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
    theme_minimal(base_size = 14) +
    labs(
      title = title_text,
      x = "Specificity",
      y = "Sensitivity"
    ) +
    annotate(
      "label",
      x = 0.78,
      y = 0.18,
      label = label_text,
      size = 4.5,
      color = "black",
      fill = scales::alpha("white", 0.85),
      label.r = grid::unit(0.1, "lines"),
      hjust = 1
    ) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank(),
      axis.line = element_line(color = "black"),
      plot.title = element_text(hjust = 0.5, face = "bold")
    )
}

plot_mdg <- function(importance_df, title_text, fill_color, top_n = 10) {
  plot_df <- importance_df[order(-importance_df$MeanDecreaseGini), , drop = FALSE]
  plot_df <- plot_df[1:min(top_n, nrow(plot_df)), , drop = FALSE]
  plot_df$miRNA <- factor(plot_df$miRNA, levels = rev(plot_df$miRNA))
  
  ggplot(plot_df, aes(x = miRNA, y = MeanDecreaseGini)) +
    geom_col(fill = fill_color) +
    coord_flip() +
    theme_minimal(base_size = 14) +
    labs(
      title = title_text,
      x = "miRNA",
      y = "Mean Decrease Gini"
    ) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black"),
      plot.title = element_text(hjust = 0.5, face = "bold")
    )
}

plot_auc_distribution <- function(auc_values, title_text, fill_color) {
  auc_df <- data.frame(AUC = auc_values)
  mean_auc <- mean(auc_values)
  sd_auc <- sd(auc_values)
  
  ggplot(auc_df, aes(x = "", y = AUC)) +
    geom_boxplot(width = 0.25, fill = fill_color, alpha = 0.7, outlier.shape = NA) +
    geom_jitter(width = 0.08, size = 2, alpha = 0.6) +
    coord_cartesian(ylim = c(0, 1)) +
    theme_minimal(base_size = 14) +
    labs(
      title = title_text,
      x = "",
      y = "AUC"
    ) +
    annotate(
      "label",
      x = 1,
      y = 0.95,
      label = paste0(
        "Mean AUC = ", round(mean_auc, 3),
        "\nSD = ", round(sd_auc, 3),
        "\nRepeats = ", length(auc_values)
      ),
      size = 4,
      fill = alpha("white", 0.7)
    ) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black"),
      plot.title = element_text(hjust = 0.5, face = "bold"),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    )
}

run_plsda_rf_cv_repeated <- function(X, y, n_repeats = 20, k = 5,
                                     ncomp = 2, n_top = 100, ntree = 500,
                                     seed = 999) {
  set.seed(seed)
  
  X <- as.matrix(X)
  y <- factor(y, levels = c("Remission", "Recidivism"))
  
  stopifnot(nrow(X) == length(y))
  stopifnot(!is.null(rownames(X)))
  
  auc_values <- c()
  rf_importance_list <- list()
  selected_feature_list <- list()
  last_all_probs <- NULL
  last_all_true  <- NULL
  
  for (r in seq_len(n_repeats)) {
    fold_assignments <- rep(NA_integer_, length(y))
    names(fold_assignments) <- rownames(X)
    
    for (cls in levels(y)) {
      cls_ids <- sample(rownames(X)[y == cls])
      fold_ids <- rep(seq_len(k), length.out = length(cls_ids))
      fold_assignments[cls_ids] <- fold_ids
    }
    
    all_probs <- c()
    all_true <- c()
    
    for (i in seq_len(k)) {
      test_ids  <- names(fold_assignments)[fold_assignments == i]
      train_ids <- setdiff(rownames(X), test_ids)
      
      X_train_full <- X[train_ids, , drop = FALSE]
      X_test_full  <- X[test_ids, , drop = FALSE]
      y_train <- factor(y[train_ids], levels = c("Remission", "Recidivism"))
      y_test  <- factor(y[test_ids], levels = c("Remission", "Recidivism"))
      
      if (length(unique(y_train)) < 2) next
      
      nzv <- apply(X_train_full, 2, sd, na.rm = TRUE) > 0
      X_train_plsda <- X_train_full[, nzv, drop = FALSE]
      X_test_plsda  <- X_test_full[, nzv, drop = FALSE]
      
      if (ncol(X_train_plsda) < 2) next
      
      colnames(X_train_plsda) <- make.unique(colnames(X_train_plsda))
      colnames(X_test_plsda)  <- colnames(X_train_plsda)
      
      plsda_fit <- plsda(X_train_plsda, y_train, ncomp = ncomp)
      load1 <- plsda_fit$loadings$X[, 1]
      load2 <- plsda_fit$loadings$X[, 2]
      loading_score <- abs(load1) + abs(load2)
      
      ranked_features <- names(sort(loading_score, decreasing = TRUE))
      selected_features <- ranked_features[1:min(n_top, length(ranked_features))]
      selected_features <- intersect(selected_features, colnames(X_train_plsda))
      selected_features <- intersect(selected_features, colnames(X_test_plsda))
      
      if (length(selected_features) < 2) next
      
      selected_feature_list[[length(selected_feature_list) + 1]] <- data.frame(
        miRNA = selected_features,
        Repeat = r,
        Fold = i,
        stringsAsFactors = FALSE
      )
      
      X_train <- X_train_plsda[, selected_features, drop = FALSE]
      X_test  <- X_test_plsda[, selected_features, drop = FALSE]
      
      rf_fit <- randomForest(
        x = X_train,
        y = y_train,
        ntree = ntree,
        importance = TRUE,
        strata = y_train,
        sampsize = rep(min(table(y_train)), 2)
      )
      
      rf_importance_list[[length(rf_importance_list) + 1]] <- data.frame(
        miRNA = rownames(rf_fit$importance),
        MeanDecreaseGini = rf_fit$importance[, "MeanDecreaseGini"],
        Repeat = r,
        Fold = i,
        stringsAsFactors = FALSE
      )
      
      y_prob <- predict(rf_fit, newdata = X_test, type = "prob")[, "Recidivism"]
      all_probs <- c(all_probs, y_prob)
      all_true  <- c(all_true, as.character(y_test))
    }
    
    if (length(unique(all_true)) < 2) next
    
    roc_obj_repeat <- roc(
      response = all_true,
      predictor = all_probs,
      levels = c("Remission", "Recidivism"),
      direction = "<"
    )
    
    auc_values <- c(auc_values, as.numeric(auc(roc_obj_repeat)))
    last_all_probs <- all_probs
    last_all_true  <- all_true
  }
  
  if (length(auc_values) == 0) {
    stop("No repeated CV AUC values were generated.")
  }
  if (length(rf_importance_list) == 0) {
    stop("No RF importance values were collected across repeats/folds.")
  }
  
  importance_df <- do.call(rbind, rf_importance_list)
  importance_summary <- aggregate(MeanDecreaseGini ~ miRNA, data = importance_df, FUN = mean)
  importance_summary <- importance_summary[order(-importance_summary$MeanDecreaseGini), ]
  
  selection_summary <- NULL
  if (length(selected_feature_list) > 0) {
    selected_df <- do.call(rbind, selected_feature_list)
    selection_summary <- aggregate(
      Repeat ~ miRNA,
      data = selected_df,
      FUN = length
    )
    colnames(selection_summary)[2] <- "SelectionCount"
    selection_summary$SelectionFrequency <- selection_summary$SelectionCount / (n_repeats * k)
    selection_summary <- selection_summary[order(-selection_summary$SelectionFrequency), ]
  }
  
  biomarker_summary <- importance_summary
  if (!is.null(selection_summary)) {
    biomarker_summary <- merge(
      importance_summary,
      selection_summary[, c("miRNA", "SelectionCount", "SelectionFrequency")],
      by = "miRNA",
      all.x = TRUE
    )
    biomarker_summary <- biomarker_summary[
      order(-biomarker_summary$MeanDecreaseGini, -biomarker_summary$SelectionFrequency),
    ]
  }
  
  roc_last <- roc(
    response = factor(last_all_true, levels = c("Remission", "Recidivism")),
    predictor = last_all_probs,
    levels = c("Remission", "Recidivism"),
    direction = "<"
  )
  
  list(
    auc_values = auc_values,
    mean_auc = mean(auc_values),
    sd_auc = sd(auc_values),
    roc_last = roc_last,
    importance = importance_summary,
    biomarker_summary = biomarker_summary,
    ranked_features = importance_summary$miRNA
  )
}

run_plsda_rf_transfer <- function(X_train_full, y_train, X_test_full, y_test,
                                  ncomp = 2, n_plsda = 100, n_rf = 100,
                                  ntree_rank = 1000, ntree_final = 1000,
                                  seed = 999) {
  set.seed(seed)
  
  X_train_full <- as.matrix(X_train_full)
  X_test_full  <- as.matrix(X_test_full)
  y_train <- factor(y_train, levels = c("Remission", "Recidivism"))
  y_test  <- factor(y_test, levels = c("Remission", "Recidivism"))
  
  stopifnot(nrow(X_train_full) == length(y_train))
  stopifnot(nrow(X_test_full) == length(y_test))
  
  nzv <- apply(X_train_full, 2, sd, na.rm = TRUE) > 0
  X_train_plsda <- X_train_full[, nzv, drop = FALSE]
  X_test_plsda  <- X_test_full[, nzv, drop = FALSE]
  
  if (ncol(X_train_plsda) < 2) {
    stop("Too few non-zero variance miRNAs available for transfer analysis.")
  }
  
  colnames(X_train_plsda) <- make.unique(colnames(X_train_plsda))
  colnames(X_test_plsda)  <- colnames(X_train_plsda)
  
  plsda_fit <- plsda(X_train_plsda, y_train, ncomp = ncomp)
  
  load1 <- plsda_fit$loadings$X[, 1]
  load2 <- plsda_fit$loadings$X[, 2]
  
  top_c1 <- names(sort(abs(load1), decreasing = TRUE)[1:min(n_plsda, length(load1))])
  top_c2 <- names(sort(abs(load2), decreasing = TRUE)[1:min(n_plsda, length(load2))])
  top_plsda_features <- union(top_c1, top_c2)
  
  X_train_rank <- X_train_plsda[, top_plsda_features, drop = FALSE]
  X_test_rank  <- X_test_plsda[, top_plsda_features, drop = FALSE]
  
  rf_rank <- randomForest(
    x = X_train_rank,
    y = y_train,
    importance = TRUE,
    ntree = ntree_rank
  )
  
  importance_df <- data.frame(
    miRNA = rownames(rf_rank$importance),
    MeanDecreaseGini = rf_rank$importance[, "MeanDecreaseGini"],
    stringsAsFactors = FALSE
  )
  importance_df <- importance_df[order(-importance_df$MeanDecreaseGini), ]
  ranked_features <- importance_df$miRNA
  
  selected_features <- ranked_features[1:min(n_rf, length(ranked_features))]
  selected_features <- intersect(selected_features, colnames(X_train_rank))
  selected_features <- intersect(selected_features, colnames(X_test_rank))
  
  if (length(selected_features) < 2) {
    stop("Too few selected miRNAs remained for transfer analysis.")
  }
  
  X_train <- X_train_rank[, selected_features, drop = FALSE]
  X_test  <- X_test_rank[, selected_features, drop = FALSE]
  
  rf_final <- randomForest(
    x = X_train,
    y = y_train,
    ntree = ntree_final,
    importance = TRUE
  )
  
  y_pred <- predict(rf_final, X_test)
  y_prob <- predict(rf_final, X_test, type = "prob")[, "Recidivism"]
  
  roc_obj <- roc(
    response = y_test,
    predictor = y_prob,
    levels = c("Remission", "Recidivism"),
    direction = "<"
  )
  
  list(
    roc = roc_obj,
    auc = as.numeric(auc(roc_obj)),
    ci = ci.auc(roc_obj),
    accuracy = mean(y_pred == y_test),
    confusion_matrix = table(True = y_test, Predicted = y_pred),
    importance = importance_df,
    ranked_features = ranked_features,
    selected_features = selected_features,
    plsda = plsda_fit
  )
}

make_clean_id <- function(x) {
  x <- trimws(x)
  x <- gsub("_", ".", x)
  x <- gsub("-", ".", x)
  x
}

# ============================================================
# 3. Healthy-only cohort splits
# ============================================================

X_tcga <- expr_healthy[grepl("^TCGA", rownames(expr_healthy)), , drop = FALSE]
y_tcga <- factor(labels_healthy[grepl("^TCGA", rownames(expr_healthy))], levels = c("Remission", "Recidivism"))

X_ki <- expr_healthy[!grepl("^TCGA", rownames(expr_healthy)), , drop = FALSE]
y_ki <- factor(labels_healthy[!grepl("^TCGA", rownames(expr_healthy))], levels = c("Remission", "Recidivism"))

stopifnot(nrow(X_tcga) == length(y_tcga))
stopifnot(nrow(X_ki) == length(y_ki))

# ============================================================
# 4. PLS-DA visualization (training cohorts)
# ============================================================

non_zero_tcga <- apply(X_tcga, 2, sd, na.rm = TRUE) > 0
X_tcga_pls <- X_tcga[, non_zero_tcga, drop = FALSE]
plsda_tcga <- plsda(X_tcga_pls, y_tcga, ncomp = 2)
p_plsda_tcga <- plot_plsda_scores(plsda_tcga, y_tcga, "SF-5H")
ggsave(file.path(figure_dir, "healthy_mirna_plsda_tcga.pdf"), p_plsda_tcga, width = 5, height = 4)

non_zero_ki <- apply(X_ki, 2, sd, na.rm = TRUE) > 0
X_ki_pls <- X_ki[, non_zero_ki, drop = FALSE]
plsda_ki <- plsda(X_ki_pls, y_ki, ncomp = 2)
p_plsda_ki <- plot_plsda_scores(plsda_ki, y_ki, "SF-5E")
ggsave(file.path(figure_dir, "healthy_mirna_plsda_ki.pdf"), p_plsda_ki, width = 5, height = 4)

# ============================================================
# 5. Within-cohort repeated cross-validation
# ============================================================

message("Running TCGA repeated 5-fold CV...")
res_tcga_cv <- run_plsda_rf_cv_repeated(
  X_tcga, y_tcga,
  n_repeats = 20, k = 5, ncomp = 2, n_top = 100, ntree = 500
)
ranked_mirna_tcga_cv <- res_tcga_cv$ranked_features
biomarker_summary_tcga_healthy_miRNA_cv <- res_tcga_cv$biomarker_summary

p_auc_tcga_cv <- plot_auc_distribution(res_tcga_cv$auc_values, "SF-5D", "springgreen4")
ggsave(file.path(figure_dir, "healthy_mirna_auc_distribution_tcga_cv.pdf"), p_auc_tcga_cv, width = 5, height = 4)

p_roc_tcga_cv <- plot_roc_curve(
  res_tcga_cv$roc_last, res_tcga_cv$mean_auc, NULL,
  "SF-5C", "springgreen4"
)
ggsave(file.path(figure_dir, "healthy_mirna_roc_tcga_cv_last_repeat.pdf"), p_roc_tcga_cv, width = 5, height = 4)

message("Running KI repeated 5-fold CV...")
res_ki_cv <- run_plsda_rf_cv_repeated(
  X_ki, y_ki,
  n_repeats = 20, k = 5, ncomp = 2, n_top = 100, ntree = 500
)
ranked_mirna_ki_cv <- res_ki_cv$ranked_features
biomarker_summary_ki_healthy_miRNA_cv <- res_ki_cv$biomarker_summary

p_auc_ki_cv <- plot_auc_distribution(res_ki_cv$auc_values, "SF-5B", "violetred4")
ggsave(file.path(figure_dir, "healthy_mirna_auc_distribution_ki_cv.pdf"), p_auc_ki_cv, width = 5, height = 4)

p_roc_ki_cv <- plot_roc_curve(
  res_ki_cv$roc_last, res_ki_cv$mean_auc, NULL,
  "SF-5A", "violetred4"
)
ggsave(file.path(figure_dir, "healthy_mirna_roc_ki_cv_last_repeat.pdf"), p_roc_ki_cv, width = 5, height = 4)

cv_summary <- data.frame(
  Model = c("TCGA repeated CV", "KI repeated CV"),
  Mean_AUC = c(res_tcga_cv$mean_auc, res_ki_cv$mean_auc),
  SD_AUC = c(res_tcga_cv$sd_auc, res_ki_cv$sd_auc),
  Repeats = c(length(res_tcga_cv$auc_values), length(res_ki_cv$auc_values)),
  stringsAsFactors = FALSE
)
write.csv(cv_summary, file.path(output_dir, "healthy_mirna_repeated_cv_summary.csv"), row.names = FALSE)

write.csv(
  biomarker_summary_tcga_healthy_miRNA_cv,
  file.path(output_dir, "healthy_mirna_biomarker_summary_tcga_cv.csv"),
  row.names = FALSE
)
write.csv(
  biomarker_summary_ki_healthy_miRNA_cv,
  file.path(output_dir, "healthy_mirna_biomarker_summary_ki_cv.csv"),
  row.names = FALSE
)

# ============================================================
# 6. Cross-cohort transfer analyses
# ============================================================

message("Running TCGA to KI transfer analysis...")
res_tcga_ki <- run_plsda_rf_transfer(X_tcga, y_tcga, X_ki, y_ki)
ranked_mirna_tcga_ki <- res_tcga_ki$ranked_features

p_roc_tcga_ki <- plot_roc_curve(
  res_tcga_ki$roc, res_tcga_ki$auc, res_tcga_ki$ci,
  "SF-5I", "springgreen4"
)
ggsave(file.path(figure_dir, "healthy_mirna_roc_tcga_to_ki.pdf"), p_roc_tcga_ki, width = 5, height = 4)

p_mdg_tcga_ki <- plot_mdg(
  res_tcga_ki$importance,
  "SF-5J",
  "springgreen4",
  top_n = 10
)
ggsave(file.path(figure_dir, "healthy_mirna_mdg_tcga_to_ki.pdf"), p_mdg_tcga_ki, width = 5, height = 4)

message("Running KI to TCGA transfer analysis...")
res_ki_tcga <- run_plsda_rf_transfer(X_ki, y_ki, X_tcga, y_tcga)
ranked_mirna_ki_tcga <- res_ki_tcga$ranked_features

p_roc_ki_tcga <- plot_roc_curve(
  res_ki_tcga$roc, res_ki_tcga$auc, res_ki_tcga$ci,
  "SF-5F", "violetred4"
)
ggsave(file.path(figure_dir, "healthy_mirna_roc_ki_to_tcga.pdf"), p_roc_ki_tcga, width = 5, height = 4)

p_mdg_ki_tcga <- plot_mdg(
  res_ki_tcga$importance,
  "SF-5G",
  "violetred4",
  top_n = 10
)
ggsave(file.path(figure_dir, "healthy_mirna_mdg_ki_to_tcga.pdf"), p_mdg_ki_tcga, width = 5, height = 4)

transfer_summary <- data.frame(
  Model = c("TCGA -> KI", "KI -> TCGA"),
  AUC = c(res_tcga_ki$auc, res_ki_tcga$auc),
  CI_lower = c(res_tcga_ki$ci[1], res_ki_tcga$ci[1]),
  CI_upper = c(res_tcga_ki$ci[3], res_ki_tcga$ci[3]),
  Accuracy = c(res_tcga_ki$accuracy, res_ki_tcga$accuracy),
  stringsAsFactors = FALSE
)
write.csv(transfer_summary, file.path(output_dir, "healthy_mirna_transfer_summary.csv"), row.names = FALSE)

write.csv(res_tcga_ki$importance, file.path(output_dir, "healthy_mirna_importance_tcga_to_ki.csv"), row.names = FALSE)
write.csv(res_ki_tcga$importance, file.path(output_dir, "healthy_mirna_importance_ki_to_tcga.csv"), row.names = FALSE)

# ============================================================
# 7. miRNA correlation with ribosome and immune programs
# ============================================================

if (!file.exists(program_file)) {
  stop("Program score file not found: ", program_file, ". Run the healthy mRNA script first.")
}

program_df <- read.csv(program_file, stringsAsFactors = FALSE)

expr_ids_raw   <- rownames(expr_healthy)
prog_ids_raw   <- program_df$Sample

expr_ids_clean <- make_clean_id(expr_ids_raw)
prog_ids_clean <- make_clean_id(prog_ids_raw)

common_ids <- intersect(expr_ids_clean, prog_ids_clean)

if (length(common_ids) == 0) {
  stop("No overlapping samples were found between miRNA healthy data and mRNA program scores.")
}

expr_idx <- match(common_ids, expr_ids_clean)
prog_idx <- match(common_ids, prog_ids_clean)

expr_healthy_mirna_matched <- expr_healthy[expr_idx, , drop = FALSE]
program_df_matched <- program_df[prog_idx, , drop = FALSE]

rownames(expr_healthy_mirna_matched) <- common_ids
program_df_matched$Sample <- common_ids

stopifnot(identical(rownames(expr_healthy_mirna_matched), program_df_matched$Sample))

program_df_matched$Outcome <- factor(program_df_matched$Outcome, levels = c("Remission", "Recidivism"))
program_df_matched$Cohort  <- factor(program_df_matched$Cohort, levels = c("KI", "TCGA"))

top_ki <- head(biomarker_summary_ki_healthy_miRNA_cv$miRNA, 15)
top_tcga <- head(biomarker_summary_tcga_healthy_miRNA_cv$miRNA, 15)

mirnas_to_test <- unique(c(top_ki, top_tcga))
mirnas_to_test <- intersect(mirnas_to_test, colnames(expr_healthy_mirna_matched))

if (length(mirnas_to_test) == 0) {
  stop("No selected miRNAs were found in the matched healthy miRNA matrix.")
}

cor_results <- lapply(mirnas_to_test, function(mir) {
  x <- expr_healthy_mirna_matched[, mir]
  
  cor_ribo <- suppressWarnings(cor.test(x, program_df_matched$Ribosome, method = "spearman"))
  cor_immune <- suppressWarnings(cor.test(x, program_df_matched$Immune, method = "spearman"))
  
  data.frame(
    miRNA = mir,
    Program = c("Ribosome", "Immune"),
    Rho = c(unname(cor_ribo$estimate), unname(cor_immune$estimate)),
    Pvalue = c(cor_ribo$p.value, cor_immune$p.value),
    stringsAsFactors = FALSE
  )
})

cor_df <- do.call(rbind, cor_results)
cor_df$FDR <- p.adjust(cor_df$Pvalue, method = "BH")
cor_df$Signif <- dplyr::case_when(
  cor_df$FDR < 0.001 ~ "***",
  cor_df$FDR < 0.01  ~ "**",
  cor_df$FDR < 0.05  ~ "*",
  TRUE ~ ""
)

cor_df <- cor_df %>% arrange(FDR, desc(abs(Rho)))
write.csv(cor_df, file.path(output_dir, "healthy_mirna_program_correlations.csv"), row.names = FALSE)

top_ribo <- cor_df %>%
  filter(Program == "Ribosome") %>%
  arrange(desc(abs(Rho))) %>%
  slice_head(n = 8)

top_immune <- cor_df %>%
  filter(Program == "Immune") %>%
  arrange(desc(abs(Rho))) %>%
  slice_head(n = 8)

top_plot_mirnas <- unique(c(as.character(top_ribo$miRNA), as.character(top_immune$miRNA)))

cor_df_plot <- cor_df %>%
  filter(miRNA %in% top_plot_mirnas)

miRNA_order <- cor_df_plot %>%
  pivot_wider(names_from = Program, values_from = Rho) %>%
  arrange(Ribosome, Immune) %>%
  pull(miRNA) %>%
  unique()

cor_df_plot$miRNA <- factor(cor_df_plot$miRNA, levels = miRNA_order)
cor_df_plot$Program <- factor(cor_df_plot$Program, levels = c("Ribosome", "Immune"))

p_cor <- ggplot(cor_df_plot, aes(x = Program, y = miRNA)) +
  geom_point(aes(size = abs(Rho), color = Rho)) +
  geom_text(aes(label = Signif), nudge_x = 0.16, size = 3.8) +
  scale_color_gradient2(
    low = "#2C7BB6",
    mid = "white",
    high = "#D7191C",
    midpoint = 0,
    limits = c(-1, 1)
  ) +
  scale_size(range = c(3, 9)) +
  theme_minimal(base_size = 12) +
  labs(
    title = "Fig. 3G",
    x = NULL,
    y = NULL,
    color = "Spearman rho",
    size = "|rho|"
  ) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 11, face = "bold"),
    legend.title = element_text(face = "bold"),
    plot.margin = ggplot2::margin(4, 4, 4, 50)
  )

ggsave(file.path(figure_dir, "healthy_mirna_program_correlations.pdf"), p_cor, width = 7, height = 6)

# ============================================================
# 8. Representative miRNA expression in healthy tissue
# ============================================================

cor_df_clean <- cor_df %>%
  filter(!is.na(miRNA), !is.na(Rho), !is.na(FDR))

top_expr_mirnas <- cor_df_clean %>%
  group_by(miRNA) %>%
  summarise(
    best_rho = max(abs(Rho), na.rm = TRUE),
    best_fdr = min(FDR, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(best_fdr, desc(best_rho)) %>%
  slice_head(n = 2) %>%
  pull(miRNA)

top_expr_mirnas <- top_expr_mirnas[top_expr_mirnas %in% colnames(expr_healthy)]

if (length(top_expr_mirnas) == 0) {
  warning("No representative miRNAs were selected for expression plotting.")
} else {
  
  # Build metadata directly from miRNA healthy data
  plot_metadata <- data.frame(
    Sample = rownames(expr_healthy),
    Outcome = factor(labels_healthy[rownames(expr_healthy)], levels = c("Remission", "Recidivism")),
    Cohort = ifelse(grepl("^TCGA", rownames(expr_healthy)), "TCGA", "KI"),
    stringsAsFactors = FALSE
  )
  
  expr_sub <- expr_healthy[, top_expr_mirnas, drop = FALSE]
  expr_sub <- data.frame(
    Sample = rownames(expr_sub),
    expr_sub,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  
  plot_df_expr <- expr_sub %>%
    pivot_longer(
      cols = all_of(top_expr_mirnas),
      names_to = "miRNA",
      values_to = "Expression"
    ) %>%
    left_join(plot_metadata, by = "Sample") %>%
    filter(!is.na(Outcome), !is.na(Cohort))
  
  plot_df_expr$miRNA <- factor(plot_df_expr$miRNA, levels = top_expr_mirnas)
  plot_df_expr$Outcome <- factor(plot_df_expr$Outcome, levels = c("Remission", "Recidivism"))
  plot_df_expr$Cohort <- factor(plot_df_expr$Cohort, levels = c("KI", "TCGA"))
  
  stats_df <- plot_df_expr %>%
    group_by(miRNA, Cohort) %>%
    summarise(
      n_groups = n_distinct(Outcome[!is.na(Outcome)]),
      p_value = if (n_groups < 2) {
        NA_real_
      } else {
        tryCatch(
          suppressWarnings(wilcox.test(Expression ~ Outcome, exact = FALSE)$p.value),
          error = function(e) NA_real_
        )
      },
      y_min = min(Expression, na.rm = TRUE),
      y_max = max(Expression, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(
      y_pos = ifelse(
        is.finite(y_max) & is.finite(y_min),
        y_max + 0.08 * pmax(y_max - y_min, 0.1),
        NA_real_
      ),
      signif = case_when(
        is.na(p_value) ~ "ns",
        p_value < 0.001 ~ "***",
        p_value < 0.01 ~ "**",
        p_value < 0.05 ~ "*",
        TRUE ~ "ns"
      ),
      x = 1.5
    )
  
  write.csv(plot_df_expr, file.path(output_dir, "healthy_mirna_expression_plot_df.csv"), row.names = FALSE)
  write.csv(stats_df, file.path(output_dir, "healthy_mirna_expression_plot_stats.csv"), row.names = FALSE)
  
  p_miRNA_by_cohort <- ggplot(plot_df_expr, aes(x = Outcome, y = Expression, fill = Outcome)) +
    geom_boxplot(width = 0.65, outlier.shape = NA, alpha = 0.85) +
    geom_jitter(width = 0.12, size = 1.5, alpha = 0.7) +
    facet_grid(miRNA ~ Cohort, scales = "free_y") +
    geom_text(
      data = stats_df,
      aes(x = x, y = y_pos, label = signif),
      inherit.aes = FALSE,
      size = 5
    ) +
    scale_fill_manual(values = c("Remission" = "#377EB8", "Recidivism" = "#E41A1C")) +
    theme_minimal(base_size = 11) +
    labs(
      title = "SF-5K",
      x = NULL,
      y = "log2 expression"
    ) +
    theme(
      legend.position = "none",
      panel.grid.minor = element_blank(),
      strip.text = element_text(face = "bold"),
      plot.title = element_text(hjust = 0.5, face = "bold")
    )
  
  ggsave(
    file.path(figure_dir, "healthy_mirna_expression_by_cohort.pdf"),
    p_miRNA_by_cohort,
    width = 7,
    height = 5
  )
}
